"""Read-only regression for the dedicated Trading Readiness page."""
import os
from pathlib import Path
os.environ.setdefault("FLASK_SECRET_KEY","trading-readiness-regression")
from webapp.app import app
from webapp.services.trading_readiness_service import get_trading_readiness

def require(value,label):
    if not value:raise AssertionError(label)
    print(f"[PASS] {label}")

def main():
    payload=get_trading_readiness()
    require(payload["status"]=="NOT_AUTHORIZED","Preparation remains not authorized")
    require(payload["live_trading_enabled"] is False,"Live trading disabled")
    require(payload["brokerage_orders"] is False,"Brokerage orders off")
    require(payload["credentials_in_repository"] is False,"No credentials exposed")
    require(payload["broker"]=="UNSELECTED","Broker unselected")
    require(len(payload["contract_sha256"])==64,"Contract SHA displayed")
    require(payload["paper_engineering"]["brokerage_orders"] is False,"Paper checkpoint exposes no brokerage authority")
    require(payload["paper_engineering"]["live_credentials"] is False,"Paper checkpoint exposes no live credentials")
    require(payload["paper_engineering"]["signal_provenance"] is True,"Signal provenance checkpoint verified")
    require(payload["paper_engineering"]["sandbox_orchestration"] is True,"Sandbox orchestration checkpoint verified")
    require(payload["paper_engineering"]["persistent_paper_shadow"] is True,"Persistent paper shadow checkpoint verified")
    require(payload["paper_engineering"]["controlled_signal_bridge"] is True,"Controlled signal bridge checkpoint verified")
    require(payload["paper_engineering"]["paper_shadow_scheduler"] is True,"Paper-shadow scheduler checkpoint verified")
    require(payload["paper_engineering"]["scheduler_monitor_only"] is True,"Scheduler remains monitor-only")
    require(payload["paper_engineering"]["operational_change_control"] is True,"Operational change control verified")
    require(payload["paper_engineering"]["protected_runtime_locked"] is True,"Paper runtime files are locked")
    require(payload["paper_engineering"]["day_zero_activation_audit"] is True,"Day-zero activation audit checkpoint verified")
    require(payload["paper_engineering"]["manual_approval_ceremony"] is True,"Manual approval ceremony checkpoint verified")
    audit=payload["paper_shadow_activation_audit"]
    require(audit["status"] in {"WAITING_FOR_BOUNDARY","READY_FOR_MANUAL_APPROVAL"},"Activation audit state is eligible")
    require(audit["manual_approval_required"] is True,"Separate manual approval is mandatory")
    require(audit["activation_performed"] is False,"Readiness page exposes no activation")
    require(audit["paper_signal_export"] is False,"Readiness page exposes no signal export")
    require(audit["brokerage_orders"] is False,"Activation audit has no brokerage authority")
    approval=payload["paper_shadow_manual_approval"]
    require(approval["status"] in {"NOT_PRESENT","VALID_FOR_SEPARATE_ACTIVATION_STEP"},"Manual approval state is explicit")
    require(approval["activation_performed"] is False,"Approval validator cannot activate")
    require(approval["paper_signal_export"] is False,"Approval validator cannot export signals")
    require(approval["brokerage_orders"] is False,"Approval validator has no brokerage authority")
    require(payload["paper_shadow_bridge"]["status"]=="PREREGISTERED_DISABLED","Controlled signal bridge remains disabled")
    require(payload["paper_shadow_bridge"]["activation_mode"]=="MANUAL_SEPARATE_APPROVAL","Bridge requires manual approval")
    require(payload["paper_shadow_bridge"]["brokerage_orders"] is False,"Bridge has no brokerage authority")
    require(payload["paper_shadow_bridge"]["holdout_outcomes_read"] is False,"Bridge reads no holdout outcomes")
    require(payload["paper_shadow_scheduler"]["brokerage_orders"] is False,"Scheduler has no brokerage authority")
    require(payload["paper_shadow_scheduler"]["holdout_outcomes_read"] is False,"Scheduler reads no holdout outcomes")
    require(payload["paper_shadow_scheduler"]["signal_exports"] == 0,"Disabled scheduler exports no signals")
    require(payload["paper_shadow"]["status"] in {"EMPTY_READY","HEALTHY"},"Paper shadow account is readable")
    require(payload["paper_shadow"]["starting_cash"]=="5000","Paper shadow starts at $5,000")
    require(payload["paper_shadow"]["reconciled"] is True,"Paper shadow account reconciles")
    require(payload["paper_shadow"]["brokerage_orders"] is False,"Paper shadow has no brokerage authority")
    app.config.update(TESTING=True,SESSION_COOKIE_SECURE=False)
    client=app.test_client()
    require(client.get("/trading-readiness").status_code in {302,401},"Page requires authentication")
    with client.session_transaction() as state:
        state["authenticated"]=True
        state["last_activity_utc"]="2026-08-25T00:00:00+00:00"
    # Use a current activity timestamp so the five-minute guard does not expire the test.
    from datetime import datetime,timezone
    with client.session_transaction() as state:state["last_activity_utc"]=datetime.now(timezone.utc).isoformat()
    response=client.get("/trading-readiness")
    require(response.status_code==200,"Authenticated page responds")
    require(b"Real Trading Readiness" in response.data,"Readiness content rendered")
    require(b"TRADING READINESS" in response.data,"Dedicated navigation tab rendered")
    require(b"PAPER EXECUTION ENGINEERING" in response.data,"Paper execution checkpoint panel rendered")
    require(b"Mode: PAPER ONLY" in response.data,"Paper-only safety boundary rendered")
    require(b"SIGNAL PROVENANCE" in response.data,"Signal provenance status rendered")
    require(b"SANDBOX ORCHESTRATION" in response.data,"Sandbox orchestration status rendered")
    require(b"OPERATIONAL LOCK" in response.data and b"LOCKED" in response.data,"Operational lock status rendered")
    require(b"PERSISTENT PAPER-SHADOW ACCOUNT" in response.data,"Persistent paper-shadow panel rendered")
    require(b"Restart-Safe $5,000 Simulation" in response.data,"Paper-shadow starting capital rendered")
    require(b"Signal provenance required" in response.data,"Paper-shadow provenance boundary rendered")
    require(b"CONTROLLED SIGNAL BRIDGE" in response.data,"Controlled signal bridge panel rendered")
    require(b"Frozen V8" in response.data and b"Provenance-Sealed Paper Signals" in response.data,"Frozen V8 bridge identity rendered")
    require(b"PREREGISTERED DISABLED" in response.data,"Disabled bridge state rendered")
    require(b"MANUAL APPROVAL" in response.data,"Manual bridge approval rendered")
    require(b"PAPER-SHADOW OPERATIONS" in response.data,"Scheduler operations panel rendered")
    require(b"Automated Scheduler" in response.data and b"Fail-Closed Monitor" in response.data,"Scheduler monitor identity rendered")
    require(b"SIGNAL EXPORTS" in response.data,"Signal-export safety state rendered")
    require(b"Monitor-only safety" in response.data,"Monitor-only boundary rendered")
    require(b"DAY-ZERO ACTIVATION AUDIT" in response.data,"Day-zero audit panel rendered")
    require(b"MANUAL APPROVAL CEREMONY" in response.data,"Manual approval ceremony panel rendered")
    require(b"Human-Reviewed Paper-Only Authorization" in response.data,"Paper-only approval boundary rendered")
    require(b"September 1 Eligibility" in response.data,"Activation boundary rendered")
    require(b"ACTIVATION PERFORMED" in response.data and b"MANUAL APPROVAL" in response.data,"Manual-only activation boundary rendered")
    require(b"LIVE ORDERS" in response.data and b"OFF" in response.data,"Live orders remain visibly off")
    require(b"type=\"password\"" not in response.data and b"API_KEY" not in response.data,"No credential controls or secrets rendered")
    source=(Path(__file__).resolve().parents[2]/"webapp/templates/trading_readiness.html").read_text()
    require("<form" not in source,"Page has no activation or order forms")
    print("\nStatus: PASSED")
    print("Page authority: READ ONLY")
    print("Brokerage orders: OFF")

if __name__=="__main__":main()
