"""Crypto XRP V1 Phase 3: OOS confidence and economic diagnostics.

This phase consumes only the out-of-sample predictions generated by Phase 2.

No model fitting occurs here.

Primary objective
-----------------
Determine whether stronger XRP Ridge predictions correspond to stronger
realized 4-hour BTC-relative returns and higher directional accuracy.

The analysis is descriptive and diagnostic only. It does not select or promote
a live threshold.

Diagnostics
-----------
- prediction-magnitude deciles
- signed prediction deciles
- absolute-confidence buckets
- positive/negative signal asymmetry
- per-fold stability
- realized BTC-relative returns
- direction hit rate
- observation coverage
- simple equal-observation cumulative diagnostic curves

Safety boundaries
-----------------
- no model retraining
- no future holdout rows
- no threshold tuning for live use
- no portfolio sizing
- no transaction-cost claims
- no brokerage execution
- no modification of frozen Crypto 15m V2
"""
from __future__ import annotations

import argparse
from datetime import datetime, timezone
import json
from pathlib import Path

import numpy as np
import pandas as pd

from ml.crypto_xrp_v1 import RESEARCH_VERSION


PHASE2_ROOT = Path(
    "data/model/crypto_xrp_v1/phase2"
)

PREDICTIONS_PATH = (
    PHASE2_ROOT / "predictions.parquet"
)

OUTPUT_ROOT = Path(
    "data/model/crypto_xrp_v1/phase3"
)

FUTURE_HOLDOUT_START = pd.Timestamp(
    "2026-09-01T00:00:00Z"
)

PRIMARY_MODEL = "ridge"

SIGNED_DECILES_PATH = (
    OUTPUT_ROOT / "signed_deciles.csv"
)

ABS_CONFIDENCE_PATH = (
    OUTPUT_ROOT / "absolute_confidence_deciles.csv"
)

SIGN_ASYMMETRY_PATH = (
    OUTPUT_ROOT / "sign_asymmetry.csv"
)

FOLD_CONFIDENCE_PATH = (
    OUTPUT_ROOT / "fold_confidence.csv"
)

CONFIDENCE_SUMMARY_PATH = (
    OUTPUT_ROOT / "confidence_summary.csv"
)

MANIFEST_PATH = (
    OUTPUT_ROOT / "manifest.json"
)


def load_predictions(
    path: Path = PREDICTIONS_PATH,
) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError(
            f"Missing Phase 2 predictions: {path}"
        )

    df = pd.read_parquet(path).copy()

    required = {
        "timestamp_utc",
        "product_id",
        "segment_id",
        "actual",
        "predicted_score",
        "model_id",
        "fold_id",
    }

    missing = required - set(df.columns)

    if missing:
        raise RuntimeError(
            "Phase 2 predictions missing required "
            f"columns: {sorted(missing)}"
        )

    df["timestamp_utc"] = pd.to_datetime(
        df["timestamp_utc"],
        utc=True,
    )

    if (
        df["timestamp_utc"]
        >= FUTURE_HOLDOUT_START
    ).any():
        raise RuntimeError(
            "Phase 3 input contains future-holdout rows"
        )

    if set(
        df["product_id"]
        .dropna()
        .unique()
    ) != {"XRP-USD"}:
        raise RuntimeError(
            "Phase 3 input contains non-XRP products"
        )

    ridge = df[
        df["model_id"] == PRIMARY_MODEL
    ].copy()

    if ridge.empty:
        raise RuntimeError(
            f"No predictions found for {PRIMARY_MODEL}"
        )

    ridge = (
        ridge.sort_values(
            ["timestamp_utc", "fold_id"]
        )
        .reset_index(drop=True)
    )

    if ridge[
        [
            "actual",
            "predicted_score",
        ]
    ].isna().any().any():
        raise RuntimeError(
            "Ridge predictions contain missing values"
        )

    ridge["actual"] = ridge[
        "actual"
    ].astype(float)

    ridge["predicted_score"] = ridge[
        "predicted_score"
    ].astype(float)

    ridge["abs_prediction"] = ridge[
        "predicted_score"
    ].abs()

    ridge["predicted_direction"] = np.sign(
        ridge["predicted_score"]
    )

    ridge["actual_direction"] = np.sign(
        ridge["actual"]
    )

    ridge["direction_correct"] = (
        ridge["predicted_direction"]
        == ridge["actual_direction"]
    )

    return ridge


def safe_qcut(
    series: pd.Series,
    q: int,
) -> pd.Series:
    """Rank before qcut so tied model scores cannot break bucket creation."""
    ranks = (
        series.rank(
            method="first"
        )
    )

    return pd.qcut(
        ranks,
        q=q,
        labels=False,
        duplicates="drop",
    )


def summarize_group(
    frame: pd.DataFrame,
) -> dict:
    if frame.empty:
        return {
            "observations": 0,
            "mean_prediction": np.nan,
            "median_prediction": np.nan,
            "mean_abs_prediction": np.nan,
            "mean_actual_return": np.nan,
            "median_actual_return": np.nan,
            "direction_hit_rate": np.nan,
            "actual_positive_fraction": np.nan,
            "prediction_positive_fraction": np.nan,
            "cumulative_actual_sum": np.nan,
        }

    return {
        "observations": int(
            len(frame)
        ),
        "mean_prediction": float(
            frame[
                "predicted_score"
            ].mean()
        ),
        "median_prediction": float(
            frame[
                "predicted_score"
            ].median()
        ),
        "mean_abs_prediction": float(
            frame[
                "abs_prediction"
            ].mean()
        ),
        "mean_actual_return": float(
            frame["actual"].mean()
        ),
        "median_actual_return": float(
            frame["actual"].median()
        ),
        "direction_hit_rate": float(
            frame[
                "direction_correct"
            ].mean()
        ),
        "actual_positive_fraction": float(
            (
                frame["actual"] > 0
            ).mean()
        ),
        "prediction_positive_fraction": float(
            (
                frame[
                    "predicted_score"
                ] > 0
            ).mean()
        ),
        "cumulative_actual_sum": float(
            frame["actual"].sum()
        ),
    }


def signed_deciles(
    df: pd.DataFrame,
) -> pd.DataFrame:
    work = df.copy()

    work["signed_decile"] = (
        safe_qcut(
            work["predicted_score"],
            10,
        )
    )

    rows = []

    for decile, group in work.groupby(
        "signed_decile",
        sort=True,
    ):
        rows.append(
            {
                "signed_decile": int(
                    decile
                ) + 1,
                **summarize_group(
                    group
                ),
            }
        )

    result = pd.DataFrame(rows)

    result["coverage_fraction"] = (
        result["observations"]
        / len(work)
    )

    return result


def absolute_confidence_deciles(
    df: pd.DataFrame,
) -> pd.DataFrame:
    work = df.copy()

    work["confidence_decile"] = (
        safe_qcut(
            work["abs_prediction"],
            10,
        )
    )

    rows = []

    for decile, group in work.groupby(
        "confidence_decile",
        sort=True,
    ):
        stats = summarize_group(
            group
        )

        long = group[
            group["predicted_score"] > 0
        ]

        short_like = group[
            group["predicted_score"] < 0
        ]

        rows.append(
            {
                "confidence_decile": (
                    int(decile) + 1
                ),
                **stats,
                "positive_signal_rows": int(
                    len(long)
                ),
                "negative_signal_rows": int(
                    len(short_like)
                ),
                "positive_signal_mean_actual": (
                    float(
                        long[
                            "actual"
                        ].mean()
                    )
                    if len(long)
                    else np.nan
                ),
                "negative_signal_mean_actual": (
                    float(
                        short_like[
                            "actual"
                        ].mean()
                    )
                    if len(short_like)
                    else np.nan
                ),
                "positive_signal_hit_rate": (
                    float(
                        (
                            long[
                                "actual"
                            ] > 0
                        ).mean()
                    )
                    if len(long)
                    else np.nan
                ),
                "negative_signal_hit_rate": (
                    float(
                        (
                            short_like[
                                "actual"
                            ] < 0
                        ).mean()
                    )
                    if len(short_like)
                    else np.nan
                ),
            }
        )

    result = pd.DataFrame(
        rows
    )

    result[
        "coverage_fraction"
    ] = (
        result["observations"]
        / len(work)
    )

    return result


def sign_asymmetry(
    df: pd.DataFrame,
) -> pd.DataFrame:
    rows = []

    for signal_name, mask in {
        "predicted_positive": (
            df["predicted_score"] > 0
        ),
        "predicted_negative": (
            df["predicted_score"] < 0
        ),
    }.items():
        group = df.loc[
            mask
        ].copy()

        rows.append(
            {
                "signal": signal_name,
                **summarize_group(
                    group
                ),
                "coverage_fraction": float(
                    len(group)
                    / len(df)
                ),
            }
        )

    return pd.DataFrame(
        rows
    )


def fold_confidence(
    df: pd.DataFrame,
) -> pd.DataFrame:
    rows = []

    for fold_id, fold in df.groupby(
        "fold_id",
        sort=True,
    ):
        fold = fold.copy()

        fold[
            "confidence_decile"
        ] = safe_qcut(
            fold[
                "abs_prediction"
            ],
            10,
        )

        highest = fold[
            fold[
                "confidence_decile"
            ]
            == fold[
                "confidence_decile"
            ].max()
        ].copy()

        all_stats = (
            summarize_group(
                fold
            )
        )

        high_stats = (
            summarize_group(
                highest
            )
        )

        rows.append(
            {
                "fold_id": fold_id,
                "fold_rows": int(
                    len(fold)
                ),
                "all_mean_actual": (
                    all_stats[
                        "mean_actual_return"
                    ]
                ),
                "all_direction_hit_rate": (
                    all_stats[
                        "direction_hit_rate"
                    ]
                ),
                "top_confidence_rows": int(
                    len(highest)
                ),
                "top_confidence_mean_prediction": (
                    high_stats[
                        "mean_prediction"
                    ]
                ),
                "top_confidence_mean_abs_prediction": (
                    high_stats[
                        "mean_abs_prediction"
                    ]
                ),
                "top_confidence_mean_actual": (
                    high_stats[
                        "mean_actual_return"
                    ]
                ),
                "top_confidence_direction_hit_rate": (
                    high_stats[
                        "direction_hit_rate"
                    ]
                ),
                "top_confidence_actual_positive_fraction": (
                    high_stats[
                        "actual_positive_fraction"
                    ]
                ),
            }
        )

    return pd.DataFrame(
        rows
    )


def confidence_summary(
    df: pd.DataFrame,
) -> pd.DataFrame:
    work = df.copy()

    work[
        "confidence_decile"
    ] = safe_qcut(
        work[
            "abs_prediction"
        ],
        10,
    )

    rows = []

    max_bucket = int(
        work[
            "confidence_decile"
        ].max()
    )

    # Fixed descriptive coverage levels.
    for minimum_bucket in [
        max_bucket,
        max_bucket - 1,
        max_bucket - 2,
        max_bucket - 4,
    ]:
        subset = work[
            work[
                "confidence_decile"
            ] >= minimum_bucket
        ].copy()

        stats = summarize_group(
            subset
        )

        rows.append(
            {
                "confidence_scope": (
                    f"decile_{minimum_bucket + 1}_to_10"
                ),
                "minimum_decile": (
                    minimum_bucket + 1
                ),
                "coverage_fraction": float(
                    len(subset)
                    / len(work)
                ),
                **stats,
            }
        )

    rows.append(
        {
            "confidence_scope": (
                "all_predictions"
            ),
            "minimum_decile": 1,
            "coverage_fraction": 1.0,
            **summarize_group(
                work
            ),
        }
    )

    return pd.DataFrame(
        rows
    )


def run(
    predictions_path: Path = PREDICTIONS_PATH,
    output_root: Path = OUTPUT_ROOT,
) -> dict:
    output_root = Path(
        output_root
    )

    output_root.mkdir(
        parents=True,
        exist_ok=True,
    )

    df = load_predictions(
        predictions_path
    )

    signed = signed_deciles(
        df
    )

    confidence = (
        absolute_confidence_deciles(
            df
        )
    )

    asymmetry = sign_asymmetry(
        df
    )

    fold = fold_confidence(
        df
    )

    summary = confidence_summary(
        df
    )

    signed.to_csv(
        output_root
        / "signed_deciles.csv",
        index=False,
    )

    confidence.to_csv(
        output_root
        / "absolute_confidence_deciles.csv",
        index=False,
    )

    asymmetry.to_csv(
        output_root
        / "sign_asymmetry.csv",
        index=False,
    )

    fold.to_csv(
        output_root
        / "fold_confidence.csv",
        index=False,
    )

    summary.to_csv(
        output_root
        / "confidence_summary.csv",
        index=False,
    )

    highest_confidence = (
        confidence.loc[
            confidence[
                "confidence_decile"
            ].idxmax()
        ]
    )

    manifest = {
        "research_version": (
            RESEARCH_VERSION
        ),
        "phase": 3,
        "stage": (
            "oos_confidence_economic_diagnostics"
        ),
        "generated_at_utc": (
            datetime.now(
                timezone.utc
            ).isoformat()
        ),
        "source_predictions": str(
            predictions_path
        ),
        "model_analyzed": (
            PRIMARY_MODEL
        ),
        "observation_count": int(
            len(df)
        ),
        "fold_count": int(
            df[
                "fold_id"
            ].nunique()
        ),
        "future_holdout_start_utc": (
            FUTURE_HOLDOUT_START
            .isoformat()
        ),
        "future_holdout_policy": (
            "Phase 3 consumes only Phase 2 "
            "OOS predictions created strictly "
            "before 2026-09-01 UTC."
        ),
        "analysis_contract": {
            "signed_deciles": (
                "Ten equal-observation buckets "
                "from most negative to most "
                "positive Ridge predictions."
            ),
            "absolute_confidence_deciles": (
                "Ten equal-observation buckets "
                "ranked by absolute Ridge "
                "prediction magnitude."
            ),
            "fold_confidence": (
                "Top absolute-confidence decile "
                "evaluated independently inside "
                "each Phase 2 fold."
            ),
            "confidence_summary": (
                "Fixed descriptive coverage "
                "groups: top 10%, 20%, 30%, "
                "50%, and all observations."
            ),
        },
        "highest_confidence_decile": {
            "decile": int(
                highest_confidence[
                    "confidence_decile"
                ]
            ),
            "observations": int(
                highest_confidence[
                    "observations"
                ]
            ),
            "mean_abs_prediction": float(
                highest_confidence[
                    "mean_abs_prediction"
                ]
            ),
            "mean_actual_return": float(
                highest_confidence[
                    "mean_actual_return"
                ]
            ),
            "direction_hit_rate": float(
                highest_confidence[
                    "direction_hit_rate"
                ]
            ),
        },
        "interpretation_policy": (
            "These are exploratory OOS "
            "diagnostics. Confidence buckets "
            "must not be interpreted as a "
            "pre-registered live trading "
            "threshold. Any future economic "
            "strategy requires a new research "
            "phase and untouched validation."
        ),
        "portfolio_policy": (
            "No compounding, portfolio sizing, "
            "transaction costs, leverage, "
            "shorting, derivatives, or brokerage "
            "execution are modeled."
        ),
        "shared_v2_policy": (
            "Frozen Crypto 15m V2 Phase 5 "
            "remains unchanged. XRP remains "
            "separate."
        ),
        "outputs": {
            "signed_deciles": str(
                output_root
                / "signed_deciles.csv"
            ),
            "absolute_confidence_deciles": str(
                output_root
                / "absolute_confidence_deciles.csv"
            ),
            "sign_asymmetry": str(
                output_root
                / "sign_asymmetry.csv"
            ),
            "fold_confidence": str(
                output_root
                / "fold_confidence.csv"
            ),
            "confidence_summary": str(
                output_root
                / "confidence_summary.csv"
            ),
            "manifest": str(
                output_root
                / "manifest.json"
            ),
        },
        "policy": (
            "diagnostic analysis only; no "
            "refitting, threshold promotion, "
            "portfolio simulation, live "
            "execution, or future-holdout "
            "evaluation"
        ),
        "next_step": (
            "Review whether confidence-response "
            "is monotonic and stable across "
            "folds. Only then decide whether "
            "a separately pre-registered "
            "economic Phase 4 is justified."
        ),
    }

    (
        output_root
        / "manifest.json"
    ).write_text(
        json.dumps(
            manifest,
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )

    return manifest


def main(argv=None) -> None:
    ap = argparse.ArgumentParser(
        description=__doc__
    )

    ap.add_argument(
        "--predictions",
        type=Path,
        default=PREDICTIONS_PATH,
    )

    ap.add_argument(
        "--output-root",
        type=Path,
        default=OUTPUT_ROOT,
    )

    args = ap.parse_args(
        argv
    )

    manifest = run(
        args.predictions,
        args.output_root,
    )

    print()
    print(
        "CRYPTO XRP V1 PHASE 3"
    )

    print(
        "=" * 80
    )

    print(
        f"Model: "
        f"{manifest['model_analyzed']}"
    )

    print(
        f"OOS observations: "
        f"{manifest['observation_count']:,}"
    )

    print(
        f"Folds: "
        f"{manifest['fold_count']}"
    )

    print()

    print(
        "Highest confidence decile:"
    )

    highest = manifest[
        "highest_confidence_decile"
    ]

    print(
        f"  observations: "
        f"{highest['observations']:,}"
    )

    print(
        f"  mean |prediction|: "
        f"{highest['mean_abs_prediction']:.6f}"
    )

    print(
        f"  mean realized BTC-relative "
        f"4h return: "
        f"{highest['mean_actual_return']:.6f}"
    )

    print(
        f"  direction hit rate: "
        f"{highest['direction_hit_rate']:.2%}"
    )

    print()

    print(
        "No model fitting occurred."
    )

    print(
        "No trading threshold was promoted."
    )

    print(
        "Future holdout remains untouched "
        "from 2026-09-01 UTC."
    )


if __name__ == "__main__":
    main()
